// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 6 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoder_status_button_6 = 6;
	/// <summary>PID: 6 | Type: read</summary>
	public const int encoder_status_button = 6;
	/// <summary>PID: 7 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoder_status_7 = 7;
	/// <summary>PID: 7 | Type: read</summary>
	public const int decoder_status = 7;
	/// <summary>PID: 8 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int current_compressed_bitrate_8 = 8;
	/// <summary>PID: 8 | Type: read</summary>
	public const int current_compressed_bitrate = 8;
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int auto_chroma_weight_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int auto_chroma_weight = 9;
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chroma_weight_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int chroma_weight = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int lossless_mode_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int lossless_mode = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int current_compressed_bitrate_decoder_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int current_compressed_bitrate_decoder = 12;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progression_order_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int progression_order = 13;
	/// <summary>PID: 14 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int code_block_width_14 = 14;
	/// <summary>PID: 14 | Type: read</summary>
	public const int code_block_width = 14;
	/// <summary>PID: 15 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int code_block_height_15 = 15;
	/// <summary>PID: 15 | Type: read</summary>
	public const int code_block_height = 15;
	public class Write
	{
		/// <summary>PID: 106 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoder_status_button_106 = 106;
		/// <summary>PID: 106 | Type: write</summary>
		public const int encoder_status_button = 106;
		/// <summary>PID: 107 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoder_status_107 = 107;
		/// <summary>PID: 107 | Type: write</summary>
		public const int decoder_status = 107;
		/// <summary>PID: 109 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int auto_chroma_weight_109 = 109;
		/// <summary>PID: 109 | Type: write</summary>
		public const int auto_chroma_weight = 109;
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int chroma_weight_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int chroma_weight = 110;
		/// <summary>PID: 111 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int lossless_mode_111 = 111;
		/// <summary>PID: 111 | Type: write</summary>
		public const int lossless_mode = 111;
		/// <summary>PID: 113 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int progression_order_113 = 113;
		/// <summary>PID: 113 | Type: write</summary>
		public const int progression_order = 113;
	}
}
public class WriteParameters
{
	/// <summary>PID: 106  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Encoder_status_button {get { return Protocol.GetParameter(106); }set { Protocol.SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Decoder_status {get { return Protocol.GetParameter(107); }set { Protocol.SetParameter(107, value); }}
	/// <summary>PID: 109  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Auto_chroma_weight {get { return Protocol.GetParameter(109); }set { Protocol.SetParameter(109, value); }}
	/// <summary>PID: 110  | Type: write</summary>
	public System.Object Chroma_weight {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Lossless_mode {get { return Protocol.GetParameter(111); }set { Protocol.SetParameter(111, value); }}
	/// <summary>PID: 113  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progression_order {get { return Protocol.GetParameter(113); }set { Protocol.SetParameter(113, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Title_begin_encoder__fixed { get; set; }
	object Title_begin_decoder__fixed { get; set; }
	object Title_end_generic__fixed { get; set; }
	object Encoder_status_button_6 { get; set; }
	object Encoder_status_button { get; set; }
	object Decoder_status_7 { get; set; }
	object Decoder_status { get; set; }
	object Current_compressed_bitrate_8 { get; set; }
	object Current_compressed_bitrate { get; set; }
	object Auto_chroma_weight_9 { get; set; }
	object Auto_chroma_weight { get; set; }
	object Chroma_weight_10 { get; set; }
	object Chroma_weight { get; set; }
	object Lossless_mode_11 { get; set; }
	object Lossless_mode { get; set; }
	object Current_compressed_bitrate_decoder_12 { get; set; }
	object Current_compressed_bitrate_decoder { get; set; }
	object Progression_order_13 { get; set; }
	object Progression_order { get; set; }
	object Code_block_width_14 { get; set; }
	object Code_block_width { get; set; }
	object Code_block_height_15 { get; set; }
	object Code_block_height { get; set; }
	object Encoder_status_button_106 { get; set; }
	object Decoder_status_107 { get; set; }
	object Auto_chroma_weight_109 { get; set; }
	object Chroma_weight_110 { get; set; }
	object Lossless_mode_111 { get; set; }
	object Progression_order_113 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: fixed</summary>
	public System.Object Title_begin_encoder__fixed {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: fixed</summary>
	public System.Object Title_begin_decoder__fixed {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 5  | Type: fixed</summary>
	public System.Object Title_end_generic__fixed {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 6  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoder_status_button_6 {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 6  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Encoder_status_button {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 7  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoder_status_7 {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 7  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Decoder_status {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 8  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Current_compressed_bitrate_8 {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 8  | Type: read</summary>
	public System.Object Current_compressed_bitrate {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 9  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Auto_chroma_weight_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Auto_chroma_weight {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chroma_weight_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	public System.Object Chroma_weight {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Lossless_mode_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: Enabled = 1, Disabled = 2</summary>
	public System.Object Lossless_mode {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Current_compressed_bitrate_decoder_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	public System.Object Current_compressed_bitrate_decoder {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progression_order_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progression_order {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Code_block_width_14 {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 14  | Type: read</summary>
	public System.Object Code_block_width {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 15  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Code_block_height_15 {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 15  | Type: read</summary>
	public System.Object Code_block_height {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 106  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoder_status_button_106 {get { return GetParameter(106); }set { SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoder_status_107 {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 109  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Auto_chroma_weight_109 {get { return GetParameter(109); }set { SetParameter(109, value); }}
	/// <summary>PID: 110  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chroma_weight_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: write | DISCREETS: Enabled = 1, Disabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Lossless_mode_111 {get { return GetParameter(111); }set { SetParameter(111, value); }}
	/// <summary>PID: 113  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progression_order_113 {get { return GetParameter(113); }set { SetParameter(113, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
