// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 6 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderstatus_6 = 6;
	/// <summary>PID: 6 | Type: read</summary>
	public const int encoderstatus = 6;
	/// <summary>PID: 7 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderstatus_7 = 7;
	/// <summary>PID: 7 | Type: read</summary>
	public const int decoderstatus = 7;
	/// <summary>PID: 8 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int currentcompressedbitrateencoder_8 = 8;
	/// <summary>PID: 8 | Type: read</summary>
	public const int currentcompressedbitrateencoder = 8;
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int autochromaweight_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int autochromaweight = 9;
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chromaweight_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int chromaweight = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int losslessmode_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int losslessmode = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int currentcompressedbitratedecoder_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int currentcompressedbitratedecoder = 12;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progressionorder_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int progressionorder = 13;
	/// <summary>PID: 14 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockwidth_14 = 14;
	/// <summary>PID: 14 | Type: read</summary>
	public const int codeblockwidth = 14;
	/// <summary>PID: 15 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockheight_15 = 15;
	/// <summary>PID: 15 | Type: read</summary>
	public const int codeblockheight = 15;
	public class Write
	{
		/// <summary>PID: 106 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderstatus_106 = 106;
		/// <summary>PID: 106 | Type: write</summary>
		public const int encoderstatus = 106;
		/// <summary>PID: 107 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderstatus_107 = 107;
		/// <summary>PID: 107 | Type: write</summary>
		public const int decoderstatus = 107;
		/// <summary>PID: 109 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int autochromaweight_109 = 109;
		/// <summary>PID: 109 | Type: write</summary>
		public const int autochromaweight = 109;
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int chromaweight_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int chromaweight = 110;
		/// <summary>PID: 111 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int losslessmode_111 = 111;
		/// <summary>PID: 111 | Type: write</summary>
		public const int losslessmode = 111;
		/// <summary>PID: 113 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int progressionorder_113 = 113;
		/// <summary>PID: 113 | Type: write</summary>
		public const int progressionorder = 113;
	}
}
public class WriteParameters
{
	/// <summary>PID: 106  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return Protocol.GetParameter(106); }set { Protocol.SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return Protocol.GetParameter(107); }set { Protocol.SetParameter(107, value); }}
	/// <summary>PID: 109  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Autochromaweight {get { return Protocol.GetParameter(109); }set { Protocol.SetParameter(109, value); }}
	/// <summary>PID: 110  | Type: write</summary>
	public System.Object Chromaweight {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Losslessmode {get { return Protocol.GetParameter(111); }set { Protocol.SetParameter(111, value); }}
	/// <summary>PID: 113  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progressionorder {get { return Protocol.GetParameter(113); }set { Protocol.SetParameter(113, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Valuezero__fixed { get; set; }
	object Exceptionvalue__fixed { get; set; }
	object Titlebeginencoder__fixed { get; set; }
	object Titlebegindecoder__fixed { get; set; }
	object Titleendgeneric__fixed { get; set; }
	object Encoderstatus_6 { get; set; }
	object Encoderstatus { get; set; }
	object Decoderstatus_7 { get; set; }
	object Decoderstatus { get; set; }
	object Currentcompressedbitrateencoder_8 { get; set; }
	object Currentcompressedbitrateencoder { get; set; }
	object Autochromaweight_9 { get; set; }
	object Autochromaweight { get; set; }
	object Chromaweight_10 { get; set; }
	object Chromaweight { get; set; }
	object Losslessmode_11 { get; set; }
	object Losslessmode { get; set; }
	object Currentcompressedbitratedecoder_12 { get; set; }
	object Currentcompressedbitratedecoder { get; set; }
	object Progressionorder_13 { get; set; }
	object Progressionorder { get; set; }
	object Codeblockwidth_14 { get; set; }
	object Codeblockwidth { get; set; }
	object Codeblockheight_15 { get; set; }
	object Codeblockheight { get; set; }
	object Afterstartup_dummy { get; set; }
	object Valueofcurrentbitrate__fixed { get; set; }
	object Vauleone__fixed { get; set; }
	object Valueofchromaweight__fixed { get; set; }
	object Valueofcodeblockwidth__fixed { get; set; }
	object Valueofcodeblockheight__fixed { get; set; }
	object Encoderstatus_106 { get; set; }
	object Decoderstatus_107 { get; set; }
	object Autochromaweight_109 { get; set; }
	object Chromaweight_110 { get; set; }
	object Losslessmode_111 { get; set; }
	object Progressionorder_113 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1  | Type: fixed</summary>
	public System.Object Valuezero__fixed {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 2  | Type: fixed</summary>
	public System.Object Exceptionvalue__fixed {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: fixed</summary>
	public System.Object Titlebeginencoder__fixed {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: fixed</summary>
	public System.Object Titlebegindecoder__fixed {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 5  | Type: fixed</summary>
	public System.Object Titleendgeneric__fixed {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 6  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_6 {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 6  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 7  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_7 {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 7  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 8  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Currentcompressedbitrateencoder_8 {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 8  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Currentcompressedbitrateencoder {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 9  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Autochromaweight {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 10  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Chromaweight {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Losslessmode {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Currentcompressedbitratedecoder_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Currentcompressedbitratedecoder {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Progressionorder {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockwidth_14 {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 14  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockwidth {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 15  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockheight_15 {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 15  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockheight {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 16  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 17  | Type: fixed</summary>
	public System.Object Valueofcurrentbitrate__fixed {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 18  | Type: fixed</summary>
	public System.Object Vauleone__fixed {get { return GetParameter(18); }set { SetParameter(18, value); }}
	/// <summary>PID: 19  | Type: fixed</summary>
	public System.Object Valueofchromaweight__fixed {get { return GetParameter(19); }set { SetParameter(19, value); }}
	/// <summary>PID: 20  | Type: fixed</summary>
	public System.Object Valueofcodeblockwidth__fixed {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 21  | Type: fixed</summary>
	public System.Object Valueofcodeblockheight__fixed {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 106  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_106 {get { return GetParameter(106); }set { SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_107 {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 109  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_109 {get { return GetParameter(109); }set { SetParameter(109, value); }}
	/// <summary>PID: 110  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_111 {get { return GetParameter(111); }set { SetParameter(111, value); }}
	/// <summary>PID: 113  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_113 {get { return GetParameter(113); }set { SetParameter(113, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
